// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microting.EformBackendConfigurationBase.Infrastructure.Data;

#nullable disable

namespace Microting.EformBackendConfigurationBase.Migrations
{
    [DbContext(typeof(BackendConfigurationPnDbContext))]
    [Migration("20260318000000_AddGroupIdToWorkorderCase")]
    partial class AddGroupIdToWorkorderCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
